"""Event types for the backtesting engine."""

from dataclasses import dataclass, field
from enum import Enum


class EventType(Enum):
    MARKET = "MARKET"
    SIGNAL = "SIGNAL"
    ORDER = "ORDER"
    FILL = "FILL"


class SignalType(Enum):
    BUY = "BUY"
    SELL = "SELL"
    EXIT = "EXIT"


class OrderType(Enum):
    MARKET = "MARKET"
    LIMIT = "LIMIT"


@dataclass
class MarketEvent:
    """Represents a single market data update."""
    event_type: EventType = field(default=EventType.MARKET, init=False)
    timestamp: float = 0.0
    symbol: str = ""
    open: float = 0.0
    high: float = 0.0
    low: float = 0.0
    close: float = 0.0
    volume: float = 0.0


@dataclass
class SignalEvent:
    """Generated by a Strategy when it detects a trading opportunity."""
    event_type: EventType = field(default=EventType.SIGNAL, init=False)
    timestamp: float = 0.0
    symbol: str = ""
    signal_type: SignalType = SignalType.BUY
    strength: float = 1.0  # 0.0 to 1.0
    metadata: dict = field(default_factory=dict)


@dataclass
class OrderEvent:
    """Generated by the Portfolio to execute a trade."""
    event_type: EventType = field(default=EventType.ORDER, init=False)
    timestamp: float = 0.0
    symbol: str = ""
    order_type: OrderType = OrderType.MARKET
    side: str = "BUY"
    quantity: float = 0.0
    price: float = 0.0


@dataclass
class FillEvent:
    """Generated by the Executor when an order is filled."""
    event_type: EventType = field(default=EventType.FILL, init=False)
    timestamp: float = 0.0
    symbol: str = ""
    side: str = "BUY"
    quantity: float = 0.0
    fill_price: float = 0.0
    commission: float = 0.0
    slippage: float = 0.0
